# Lint the code,
# Run tests,
# and Deploy the app
---
steps:
  # install the node dependencies
  - id: install
    name: node:10
    entrypoint: npm
    args: ['install']
  # run eslint
  - id: lint
    name: node:10
    entrypoint: npm
    args: ['run', 'lint']
    waitFor:
      - install
  # deploy the application
  - id: deploy
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '600s'
    waitFor:
      - lint
